/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Failure: typeof import('./components/failure/GameFailure.vue')['default']
    GameAward: typeof import('./components/award/GameAward.vue')['default']
    GameFailure: typeof import('./components/failure/GameFailure.vue')['default']
    LineSelect: typeof import('./components/award/LineSelect.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
    TouchSlider: typeof import('./components/TouchSlider.vue')['default']
    WordAward: typeof import('./components/award/WordAward.vue')['default']
  }
}
